language: python
os: linux
sudo: required
dist: xenial
cache:
    pip: true

python:
    - 3.7
addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libopenmpi-dev
            - openmpi-bin

before_install:
  # needed for driftscan setup
  - pip install future

  # needed for cora setup
  - pip install cython

install:
  # install h5py and bitshuffle
  - pip install --no-binary=h5py h5py
  - cd ..
  - git clone https://github.com/kiyo-masui/bitshuffle.git
  - cd bitshuffle
  - python setup.py install #[--h5plugin [--h5plugin-dir=spam]]
  - cd ../draco

  # install draco
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .

before_script:
  - pip install black

script:
    # code linting
    - black --check .

    # build docs
    - sphinx-build -b html doc/ doc/_build/html

    # unit tests
    - pytest -x

    # run (some) unit tests with mpi
    - mpirun -np 4 pytest -x test/test_selections.py
    - mpirun -np 4 pytest -x test/test_containers.py
