language: python
os: linux
sudo: required
dist: xenial
cache:
    pip: true

python:
    - 3.7
addons:
    apt:
        packages:
            - libopenmpi-dev

before_install:
  # needed for driftscan setup
  - pip install future

  # needed for cora setup
  - pip install cython

install:
  - pip install -r requirements.txt
  - pip install -r doc/requirements.txt
  - pip install .

before_script:
  - pip install black

script:
    # code linting
    - black --check .

    # build docs
    - sphinx-build -b html doc/ doc/_build/html

    # unit tests
    - pytest -x
