pipeline:
    tasks:
        -   type:       draco.core.io.LoadBeamTransfer
            out:        tel_and_bt
            params:
                product_directory:  "testbeams/bt/"

        -   type:       draco.synthesis.stream.SimulateSidereal
            requires:   tel_and_bt
            out:        sstream
            params:
                save:   Yes
                output_root: teststream_

        -   type:       draco.analysis.transform.MModeTransform
            in:         sstream
            out:        mmodes

        -   type:       draco.analysis.mapmaker.DirtyMapMaker
            requires:   tel_and_bt
            in:         mmodes
            out:        dirtymap
            params:
                nside:      128
                save:   Yes
                output_root: map_dirty2_

        -   type:       draco.analysis.mapmaker.WienerMapMaker
            requires:   tel_and_bt
            in:         mmodes
            out:        wienermap
            params:
                nside:      128
                save:   Yes
                output_root: map_wiener2_
