name: build-sphinx-to-gh-pages
on:
  push:
    branches:
    - rn/rtd
    - master

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install apt dependencies
        run: |
          sudo apt-get install -y libopenmpi-dev openmpi-bin

      - uses: actions/checkout@v2
      - name: Install pip requirements
        run: pip install -r requirements.txt
      - name: Install pip doc/requirements
        run: pip install -r doc/requirements.txt
      - name: Sphinx build
        run: |
          git checkout -b gh-pages
          cd doc
          make clean
          make html
          mkdir ../docs
          mv _build/html* ../docs/
          touch ../docs/.nojekyll
      - name: Commit site
        run: |
          git config --global user.name 'Rick Nitsche (automated)'
          git config --global user.email 'nritsche@users.noreply.github.com'
          git add .
          git commit -am "Automated sphinx build"
          git push --force origin gh-pages
